apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  labels:
    app: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: howdi2000/board:0.1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-board
spec:
  type: NodePort
  selector:
    app: board
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
      targetPort: 8080